### PR TITLE
PERA-1060 :: Add new icon next to stake bottom nav icon per figma design

### PR DESCRIPTION
**Pull request by michaeltchuang**
# Pull Request Template

## Description
- Add new icon next to existing staking bottom nav icon per figma design
- Changing "Staking" button text to "Stake"

## Related Issues
- Closes https://algorandfoundation.atlassian.net/browse/PERA-1060

## Checklist
- [X] Have you tested your changes locally?
- [X] Have you reviewed the code for any potential issues?
- [X] Have you documented any necessary changes in the project's documentation?
- [X] Have you added any necessary tests for your changes?
- [X] Have you updated any relevant dependencies?

## Additional Notes
- Missed new icon in PERA-1060 PR when merging

### CODE REVIEW

**Comment by michaeltchuang** [comment]
dark theme 
Screenshot_1733442467

light theme
Screenshot_1733442492

**Comment by mitsinsar** [comment]
Is there a specific reason for not using existing ListMenuItemView by adding label next to title?

**Comment by michaeltchuang** [comment]
> Is there a specific reason for not using existing ListMenuItemView by adding label next to title?

I was having trouble getting the margins to work for both cases (with label and non label) so I just went for speed with the copy and paste.  I figure most of this xml work is throwaway code when we move to compose anyways.  I was trying not to spend too much effort on this.

Do you think we should try to get it working with the one ListMenuItemView?  Or maybe just work on refactoring bottom sheet into compose instead?

**Comment by mitsinsar** [comment]
If it is causing you a trouble, we can keep as is since it is a quite simple UI component

**Review by mitsinsar — APPROVED** [review]

**Pull request merged**
