### PR TITLE
PERA-994 :: upgrade algosdk version

### PR DESCRIPTION
**Pull request by michaeltchuang**
## Description
- Upgrade AlgoSDK to latest stable version
- I converted `settings.gradle` to Kotlin DSL since that was simple (trying to help convert repo groovy files to new Kotlin DSL standard)

## Additional Notes
- Closes https://algorandfoundation.atlassian.net/browse/PERA-994
- I created a toml file since that's the new Android way to track dependency versions.  We can move other dependencies in future PRs.
- Pointed PR base branch at `dev`/`main` since not sure when `account-refactor` branch will be merged

### CODE REVIEW

**Comment by yigitguler** [comment]
Thank you @michaeltchuang for this PR. We will review it next week and get back to you!

**Comment by yasin-ce** [comment]
Hi @michaeltchuang, thank you for your PR! I reviewed it, and it looks good overall. However, there are a couple of points we need to address:

1. App Architecture Changes:
We are currently undergoing major changes in our app’s architecture, which you can find in the account-refactor branch. Your Gradle updates will likely cause conflicts with this branch. Could you please change the base branch of your PR to `account-refactor` and adjust your Gradle updates to fit the new structure?

2. Broken Unit and UI Tests:
At the moment, our unit and UI tests are not functioning correctly. We’re working on fixing them within the `account-refactor` branch. Once they’re ready, we plan to add GitHub workflows for running tests and lint checks.

For smoother collaboration, it would be great if you could split your PR into two:
• One for GitHub workflows.
• One for the Gradle version updates.

Let me know if you have any questions or need help with this. Thanks again for your contribution!

**Comment by michaeltchuang** [comment]
@yasin-ce I changed the PR base branch and broke up the current PR into two.  I made this one to be gradle PR and the new workflow PR is here https://github.com/perawallet/pera-android/pull/7

**Comment by michaeltchuang** [comment]
@yasin-ce just wondering, what's the difference between `algosdk.aar` library file in `account-refactor` branch and the algorand sdk dependency we pull down from mavencentral in `build.gradle`?  

i noticed some bugs on `account-refactor` branch, but i assume y'all are working through them

**Comment by yasin-ce** [comment]
`algosdk.aar` contains some custom functions we developed on top of the algorand go mobile SDK. I've talked with the team and we will make that repo public. Then you can review the functions in that repo.  @michaeltchuang 
https://github.com/perawallet/go-mobile-algorand-sdk

**Comment by michaeltchuang** [comment]
> `algosdk.aar` contains some custom functions we developed on top of the algorand go mobile SDK. I've talked with the team and we will make that repo public. Then you can review the functions in that repo. @michaeltchuang https://github.com/perawallet/go-mobile-algorand-sdk

@yasin-ce @yigitguler is there update on open sourcing this repo?  (it's still not public so i can't view it)

**Comment by yasin-ce** [comment]
Hi @michaeltchuang, we made it open source 3 weeks ago but I forgot to inform you. you can review it [here](https://github.com/perawallet/algorand-go-mobile-sdk/).

**Review by yasin-ce — APPROVED** [review]

**Pull request merged**
