### PR TITLE
PERA-735 :: Add ledger flex and stax support

### PR DESCRIPTION
**Pull request by yasin-ce**
## Summary
- Add in support for ledger flex and stax

## Testing
- Eric (QA Team) will give greenlight if this PR should be merged in since he has the test devices

## Additional Notes
- Closes https://algorandfoundation.atlassian.net/browse/PERA-735

### CODE REVIEW

**Comment by michaeltchuang** [comment]
@yasin-ce is there a JIRA ticket assigned to this work?  can you add it to PR title prefix if it exists?  

If not, let me know and we can create one for this work (or you can and reference it in this PR)

**Comment by michaeltchuang** [comment]
> @yasin-ce is there a JIRA ticket assigned to this work? can you add it to PR title prefix if it exists?
> 
> If not, let me know and we can create one for this work (or you can and reference it in this PR)

Nevermind i found it in jira - https://algorandfoundation.atlassian.net/browse/PERA-735

**Review by 1atAlcone — CHANGES_REQUESTED** [review]
Wow 😁

**Review by mchuangatalgorand — APPROVED** [review]

**Review by michaeltchuang — APPROVED** [review]
I don't have a stax or flex to test with but if Eric (QA) said checks out fine, code looks fine to me...I'll approve

**Pull request merged**
